### ISSUE TITLE
[Advanced Columns] Change response for available-columns config

### ISSUE THREAD

**Issue by martineiber** [pimcore/studio-backend-bundle#1163]
Config should not be an array it should be a object..

```yaml
"config": {
  "simpleField": [
    {
        "name": "Object Type",
        "key": "objectType"
    }, 
 ]
}
```
