### ISSUE TITLE
[Advanced Columns] Change config Schema to get data

### ISSUE THREAD

**Issue by martineiber** [pimcore/studio-backend-bundle#1164]
Is should include the key that we know if it is a simpleField, relationField

```yaml
"columns": [
    {
        "key": "advanced",
        "locale": "en",
        "type": "dataobject.advanced",
        "config": {
            "advancedColumns": [
                {
                 "key": "simpleField",
                 "config": {
                     "field": "name"
                  }
                }
            ]
        }
    }
]
```
