### ISSUE TITLE
Missing functionalities regarding asset preview

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#458]
We have some special cases regarding the asset preview which are currently missing:

* Image preview thumbnail with a higher resolution
Currently we only have the system thumbnail definition like in the classic bundle. This is fine for most cases but for the actual detail view of an asset we would need a higher resolution because our new design offers more space for the actual image + a zoom button.

* Video thumbnail generation loading state/progress
In the video preview we currently show the original asset video. We would need to show a video thumbnail there. In the classic bundle we have some kind of loading spinner while this preview is generated (can take a while...). We have already some endpoints in that direction but I'm not sure if something is missing or high exactly we need to call the endpoints to achieve the same.

* PDF preview javascript removal queue with loading state/progress
This is a similar case like the video thumbnail generation. In the classic bundle we have a messenger worker which removes javascript from PDF previews (for security reasons...). While the queue is running the classic bundle shows a loading indicator. We need the same in studio UI.

* Some months ago you mentioned that you find some special functionallities in the classic bundle regarding the asset preview. Where does the listed topics above or do you know about other special cases?

Could you please tell me who I should contact? I'd say it's better if we do a short call on those topics.

**Comment by markus-moser** [comment]
@lukmzig Please add as discussed a route for the following preview thumbnail configuration:

```yaml
items:
  - method: setBackgroundImage
    arguments:
      path: /bundles/pimcoreadmin/img/tree-preview-transparent-background.png
      mode: asTexture
  - method: contain
    arguments:
      width: 1920
      height: 1920
      forceResize: false
medias: []
name: studio-preview
format: PJPEG
quality: 60
highResolution: null
preserveColor: false
preserveMetaData: false
rasterizeSVG: false
preserveAnimation: false
```

As the image for the transparent background rasterization is provided by the classic bundle we need to copy it to studio UI. It might be the case that we need to slightly adjust this configuration in future but this should be a reasonable starting point.
