### ISSUE TITLE
Add `permissions` to grid

### ISSUE THREAD

**Issue by Corepex** [pimcore/studio-backend-bundle#663]
Please always return the `permissions` when returning the grid config in the following endpoint `/pimcore-studio/api/assets/grid`

I would just add it on the same level as `colums`

**Comment by mattamon** [comment]
Do you mean the permissions of the specific asset for the logged in user, like this?

```yaml
{
  "totalItems": 7,
  "items": [
    {
      "columns": [
        {
          "key": "id",
          "locale": "en",
          "value": 83,
          "additionalAttributes": []
        }
      ],
      "permissions": [
         "list": true,
         "view": true
         ...
      ]
    }
  ]
}
```
