### ISSUE TITLE
[Locate in Tree] Respect root node

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#859]
The locate in tree mechanism seems to work well, but there is a small problem. If the root node is enabled it's not possible to locate it with the endpoint.

![Image](https://github.com/user-attachments/assets/8ca3e8d9-12c3-4876-992f-f64a71e88669)

**Comment by mattamon** [comment]
@markus-moser could you please share your config.

For the default persective it works.
`http://localhost/pimcore-studio/api/elements/data-object/location/744/studio_default_perspective`

```json
{
  "widgetId": "studio_data_object_tree_widget",
  "treeLevelData": [
    {
      "parentId": 1,
      "elementId": 744,
      "pageNumber": 1
    }
  ],
  "additionalAttributes": []
}
```

**Comment by markus-moser** [comment]
@mattamon I tried it with this one:

```YAML
pimcore_studio_backend:

    element_tree_widgets:
        my_object_tree:
            name: 'My Object Tree Widget'
            elementType: 'data-object' # data-object, asset or document types are supported
            icon:
                type: name
                value: 'open-folder'
            rootFolder: '/Product Data'
            showRoot: true
            pageSize: 10
            contextPermissions:  []
        my_asset_tree:
            name: 'My Asset Tree Widget'
            elementType: 'asset' # data-object, asset or document types are supported
            icon:
                type: name
                value: 'asset'
            rootFolder: '/Car Images'
            showRoot: true
            pageSize: 10
            contextPermissions: []
    studio_perspectives:
        my_custom:
            name: "My Custom Perspective"
            icon: # Use null to use the default icon
                type: "path"
                value: "/path/to/custom/icon.svg"
            widgetsLeft:
                my_object_tree: "element_tree" # Array of widget ID => widget type
            widgetsRight:
                my_object_tree: "element_tree" # Array of widget ID => widget type
                my_asset_tree: "element_tree" # Array of widget ID => widget type
            widgetsBottom:
                my_object_tree: "element_tree" # Array of widget ID => widget type
            expandedLeft: my_object_tree # ID of widget which should be expanded
            expandedRight: my_asset_tree
            contextPermissions: 
                extras:
                    hidden: false
                    notesEvents: true
```
